sudo: required

language: go

go:
  - 1.5.4
  - 1.6

services:
  - docker

install:
  - make dependencies

script:
  - make stat

after_success:
  - make clean
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/beacon-client unixvoid/beacon-client:develop
  - docker push unixvoid/beacon-client:develop
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/beacon-client*` --form path=beacon-client/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/beacon-client*` --form filename=beacon-client-latest-linux-amd64 --form path=beacon-client/ https://cryo.unixvoid.com/upload
