sudo: required

language: go

go:
  - 1.5.4
  - 1.6

services:
  - docker

install:
  - make dependencies

script:
  - make stat

after_success:
  - make clean
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/beacon-client unixvoid/beacon-client:develop
  - docker push unixvoid/beacon-client:develop
