sudo: required

language: go

go:
  - 1.5.4
  - 1.6

services:
  - docker

install:
  - make dependencies

script:
  - make stat

after_success:
  - echo $testval
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    ocker push unixvoid/beacon-client:develop;
    fi
